name: grommunio

networks:
  grommunio:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
        - subnet: "fd00:1::/64"
          gateway: "fd00:1::1"

volumes:
  gromox_services:
  cert_data:
  gromox_mysql_data:
  chat_mysql_data:
  files_mysql_data:
  office_mysql_data:
  archive_mysql_data:
  grommunio_admin_api:
  grommunio_antispam:
  grommunio_dav:
  grommunio_web:
  opensuse_data:
  gromox:
  gromox_config:
  variables_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/variables_data
  gromox_letsencrypt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/gromox_letsencrypt

services:
  gromox-db:
    image: mariadb:11
    container_name: gromox-db
    environment:
      MARIADB_ROOT_PASSWORD: Lu3s3WmFxXghtLwJnuqN
      MARIADB_DATABASE: grommunio
      MARIADB_USER: grommunio
      MARIADB_PASSWORD: Lu3s3WmFxXghtLwJnuqN
    volumes:
      - gromox_mysql_data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: mariadb --host=localhost --user=$${MARIADB_USER} --password=$${MARIADB_PASSWORD} -e 'SELECT 1;'
      interval: 30s
      timeout: 10s
      retries: 5
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      grommunio:
        aliases:
          - gromox-db

  chat-db:
    image: mariadb:10
    container_name: chat-db
    environment:
      MARIADB_ROOT_PASSWORD: Lu3s3WmFxXghtLwJnuqN
      MARIADB_DATABASE: grochat
      MARIADB_USER: grochat
      MARIADB_PASSWORD: grommunio
    volumes:
      - chat_mysql_data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: mariadb --host=localhost --user=$${MARIADB_USER} --password=$${MARIADB_PASSWORD} -e 'SELECT 1;'
      interval: 30s
      timeout: 10s
      retries: 5
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      grommunio:
        aliases:
          - chat-db

  files-db:
    image: mariadb:10
    container_name: files-db
    environment:
      MARIADB_ROOT_PASSWORD: Lu3s3WmFxXghtLwJnuqN
      MARIADB_DATABASE: grofiles
      MARIADB_USER: grofiles
      MARIADB_PASSWORD: grommunio
    volumes:
      - files_mysql_data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: mariadb --host=localhost --user=$${MARIADB_USER} --password=$${MARIADB_PASSWORD} -e 'SELECT 1;'
      interval: 30s
      timeout: 10s
      retries: 5
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      grommunio:
        aliases:
          - files-db

  office-db:
    image: mariadb:10
    container_name: office-db
    environment:
      MARIADB_ROOT_PASSWORD: Lu3s3WmFxXghtLwJnuqN
      MARIADB_DATABASE: groffice
      MARIADB_USER: groffice
      MARIADB_PASSWORD: grommunio
    volumes:
      - office_mysql_data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: mariadb --host=localhost --user=$${MARIADB_USER} --password=$${MARIADB_PASSWORD} -e 'SELECT 1;'
      interval: 30s
      timeout: 10s
      retries: 5
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      grommunio:
        aliases:
          - office-db

  archive-db:
    image: mariadb:10
    container_name: archive-db
    environment:
      MARIADB_ROOT_PASSWORD: Lu3s3WmFxXghtLwJnuqN
      MARIADB_DATABASE: groarchive
      MARIADB_USER: groarchive
      MARIADB_PASSWORD: grommunio
    volumes:
      - archive_mysql_data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: mariadb --host=localhost --user=$${MARIADB_USER} --password=$${MARIADB_PASSWORD} -e 'SELECT 1;'
      interval: 30s
      timeout: 10s
      retries: 5
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      grommunio:
        aliases:
          - archive-db

  gromox-core:
    build:
      context: ./
      dockerfile: ./gromox-core/Dockerfile
    restart: on-failure
    volumes:
      - opensuse_data:/data
      - variables_data:/home/vars
      - cert_data:/etc/grommunio-common/ssl
      - gromox_services:/home/gromox-services
      - grommunio_admin_api:/var/lib/grommunio-admin-api
      - grommunio_antispam:/var/lib/grommunio-antispam
      - grommunio_dav:/var/lib/grommunio-dav
      - grommunio_web:/var/lib/grommunio-web
      - gromox:/var/lib/gromox
      - gromox_config:/etc/gromox
      - gromox_letsencrypt:/etc/letsencrypt
    ports:
      - "25:2525"    # SMTP
      - "80:8080"    # HTTP / Letsencrypt challenges
      - "443:8443"   # HTTPS / Grommunio Web
      - "465:2465"   # SMTPS
      - "993:2993"   # IMAPS
      - "110:2110"   # POP3
      - "143:2143"   # IMAP
      - "587:2587"   # SMTP Submission
      - "995:2995"   # POP3S
      - "8443:9443"  # Grommunio Admin / HTTPS alternative
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      grommunio:
        aliases:
          - gromox-core
    env_file:
      - var.env
    depends_on:
      gromox-db:
        condition: service_healthy
      chat-db:
        condition: service_healthy
      files-db:
        condition: service_healthy
      office-db:
        condition: service_healthy
      archive-db:
        condition: service_healthy

  gromox-archive:
    build:
      context: ./
      dockerfile: ./gromox-archive/Dockerfile
    restart: on-failure
    volumes:
      - opensuse_data:/data
      - variables_data:/home/vars
      - cert_data:/etc/grommunio-common/ssl
    expose:
      - "8443"   # HTTPS (nginx)
      - "2693"   # Archive SMTP
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      grommunio:
        aliases:
          - gromox-archive
    env_file:
      - var.env
    depends_on:
      gromox-db:
        condition: service_healthy
      archive-db:
        condition: service_healthy
      gromox-core:
        condition: service_started

  gromox-office:
    build:
      context: ./
      dockerfile: ./gromox-office/Dockerfile
    restart: on-failure
    volumes:
      - opensuse_data:/data
      - variables_data:/home/vars
      - cert_data:/etc/grommunio-common/ssl
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      grommunio:
        aliases:
          - gromox-office
    env_file:
      - var.env
    depends_on:
      gromox-db:
        condition: service_healthy
      files-db:
        condition: service_healthy
      office-db:
        condition: service_healthy
      gromox-core:
        condition: service_started
