apiVersion: apps/v1
kind: Deployment
metadata:
  name: gromox-deployment
  labels:
    app: gromox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gromox
  template:
    metadata:
      labels:
        app: gromox
    spec:
      containers:
      - name: gromox-event
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && /usr/libexec/gromox/event"]
        ports:
        - containerPort: 33333 
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
      - name: gromox-timer
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh &&/usr/libexec/gromox/timer"]
        ports:
        - containerPort: 6666 
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
      - name: gromox-zcore
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && /usr/libexec/gromox/zcore"]
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
      - name: gromox-midb
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && /usr/libexec/gromox/midb"]
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
      - name: gromox-http
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c']
        args:
           - /scripts/db.sh && 
             mv /etc/php7/fpm/php-fpm.conf.default /etc/php7/fpm/php-fpm.conf && 
             ln -s /home/gromox-services/* /etc/gromox/ &&
             php-fpm &&
             /usr/libexec/gromox/http
        ports:
        - containerPort: 10080
        - containerPort: 10443
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
        volumeMounts:
        - name: ssl-volume
          mountPath: /home/certificates
        - name: gromox-services-volume
          mountPath: /home/gromox-services
      - name: gromox-postfix
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh &&  ln -s /home/gromox-services/* /etc/gromox/ &&postfix start && tail -f /dev/null"]
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
        volumeMounts:
        - name: gromox-services-volume
          mountPath: /home/gromox-services
      - name: gromox-delivery-queue
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && /usr/libexec/gromox/delivery-queue"]
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
      - name: gromox-delivery
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && /usr/libexec/gromox/delivery"]
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
      - name: gromox-pop3
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && ln -s /home/gromox-services/* /etc/gromox/ && /usr/libexec/gromox/pop3"]
        ports:
        - containerPort: 995
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
        volumeMounts:
        - name: ssl-volume
          mountPath: /home/certificates
        - name: gromox-services-volume
          mountPath: /home/gromox-services
      - name: gromox-imap
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && ln -s /home/gromox-services/* /etc/gromox/ && /usr/libexec/gromox/imap"]
        ports:
        - containerPort: 993
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
        volumeMounts:
        - name: ssl-volume
          mountPath: /home/certificates
        - name: gromox-services-volume
          mountPath: /home/gromox-services
      - name: gromox-antispam
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c']
        args:
           - mkdir -p /var/run/grommunio-antispam &&
             rspamd -u groas -g grommunio &&
             redis-server &&
             ln -s /home/gromox-services/* /etc/gromox/ &&
             tail -f /dev/null
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
        volumeMounts:
        - name: ssl-volume
          mountPath: /home/certificates
        - name: gromox-services-volume
          mountPath: /home/gromox-services
      - name: gromox-admin
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c']
        args:
           - /scripts/admin-db.sh && 
             mv /etc/php7/fpm/php-fpm.conf.default /etc/php7/fpm/php-fpm.conf && 
             php-fpm && 
             grommunio-admin passwd -p $ADMIN_PASS &&
             ln -s /home/plugins/conf.yaml /etc/grommunio-admin-api/conf.d/conf.yaml &&
             /home/links/config.sh &&
             ln -s /home/links/web-config.conf /etc/grommunio-admin-common/nginx.d/web-config.conf &&
             /home/plugins/chat-conf.sh &&
             uwsgi --ini /usr/share/grommunio-admin-api/api-config.ini --daemonize /var/log/admin-api.log &&
             chown nginx:nginx /run/grommunio/admin-api.socket &&
             ln -s /home/gromox-services/* /etc/gromox/ &&
             nginx -g 'daemon off;'
        ports:
        - containerPort: 8443
        - containerPort: 80
        - containerPort: 443
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
        volumeMounts:
        - name: ssl-volume
          mountPath: /home/certificates
        - name: admin-plugins-volume
          mountPath: /home/plugins
        - name: admin-links-volume
          mountPath: /home/links 
        - name: gromox-services-volume
          mountPath: /home/gromox-services
      - name: gromox-chat
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c']
        args:
           - cd /usr/share/grommunio-chat &&
             /home/chat/setup.sh &&
             ln -s /home/gromox-services/* /etc/gromox/
        envFrom:
        - configMapRef:
            name: chat-db-config
        - configMapRef:
            name: general-config
        volumeMounts:
        - name: ssl-volume
          mountPath: /home/certificates
        - name: chat-setup-volume
          mountPath: /home/chat
        - name: gromox-services-volume
          mountPath: /home/gromox-services
      volumes:
      - name: ssl-volume
        secret:
          secretName: selfsigned-cert-tls
      - name: admin-plugins-volume
        configMap:
          name: admin-plugins-config
          defaultMode: 0777 
      - name: admin-links-volume
        configMap:
          name: admin-links-config
          defaultMode: 0777
      - name: chat-setup-volume
        configMap:
          name: chat-setup-config
          defaultMode: 0777
      - name: gromox-services-volume
        configMap:
          name: gromox-services-config
---
apiVersion: v1
kind: Service
metadata:
  name: gromox-service
spec:
  selector:
    app: gromox
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: admin
    protocol: TCP
    port: 8443
    targetPort: 8443
