[program:grommunio-archive]
command=/usr/sbin/piler -c /etc/grommunio-archive/grommunio-archive.conf
user=groarchive
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-grommunio-archive.log
stderr_logfile=/var/log/supervisor-grommunio-archive-err.log
