[program:grommunio-archive-smtp]
command=/usr/sbin/piler-smtp -c /etc/grommunio-archive/grommunio-archive.conf
user=groarchive
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-grommunio-archive-smtp.log
stderr_logfile=/var/log/supervisor-grommunio-archive-smtp-err.log
