[program:grommunio-archive-indexer-main]
command=/bin/bash -c "sleep 600; while true; do sudo -u groarchive /usr/lib/grommunio-archive/indexer.main.sh; sudo -u groarchive /usr/lib/grommunio-archive/indexer.attachment.sh; sudo -u groarchive /usr/lib/grommunio-archive/purge.sh; sudo -u groarchive /usr/bin/php /usr/lib/grommunio-archive/sign.php; sudo -u groarchive /usr/bin/php /usr/lib/grommunio-archive/generate_stats.php; sudo -u groarchive /usr/bin/php /usr/lib/grommunio-archive/daily-report.php; sleep ${ARCHIVE_INDEXER_MAIN_INTERVAL:-24h}; done"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-archive-indexer-main.log
stderr_logfile=/var/log/supervisor-archive-indexer-main-err.log
