[program:grommunio-archive-indexer]
command=/bin/bash -c "sleep 300; while true; do sudo -u groarchive /usr/bin/indexer --rotate --all; sleep 600; done"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-archive-indexer.log
stderr_logfile=/var/log/supervisor-archive-indexer-err.log
