[program:ds-converter]
command=/usr/libexec/grommunio-office/server/FileConverter/converter
environment=LD_LIBRARY_PATH="/usr/libexec/grommunio-office/server/FileConverter/bin",NODE_CONFIG_DIR="/etc/grommunio-office",NODE_ENV="production-linux"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-ds-converter.log
stderr_logfile=/var/log/supervisor-ds-converter-err.log
