[program:ds-docservice]
command=/usr/libexec/grommunio-office/server/DocService/docservice
environment=NODE_CONFIG_DIR="/etc/grommunio-office",NODE_ENV="production-linux"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-ds-docservice.log
stderr_logfile=/var/log/supervisor-ds-docservice-err.log
