[program:redis]
command=/usr/sbin/redis-server /etc/redis/grommunio.conf --daemonize no
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-redis.log
stderr_logfile=/var/log/supervisor-redis-err.log
