[program:grommunio-admin-api]
command=/usr/sbin/uwsgi --ini /usr/share/grommunio-admin-api/api-config.ini --chown-socket=root:nginx
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-grommunio-admin-api.log
stderr_logfile=/var/log/supervisor-grommunio-admin-api-err.log
