[program:grommunio-chat]
command=/usr/bin/grommunio-chat
autostart=false
autorestart=true
user=grochat
stdout_logfile=/var/log/supervisor-grommunio-chat.log
stderr_logfile=/var/log/supervisor-grommunio-chat-err.log
