[program:gromox-delivery]
command=/usr/libexec/gromox/delivery
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-gromox-delivery.log
stderr_logfile=/var/log/supervisor-gromox-delivery-err.log
