[program:grommunio-antispam]
command=/usr/bin/rspamd -c /etc/grommunio-antispam/rspamd.conf -f -u groas -g grommunio
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-grommunio-antispam.log
stderr_logfile=/var/log/supervisor-grommunio-antispam-err.log
