[program:gromox-delivery-queue]
command=/usr/libexec/gromox/delivery-queue
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-gromox-delivery-queue.log
stderr_logfile=/var/log/supervisor-gromox-delivery-queue-err.log
