[program:postfix]
command=/usr/lib/postfix/bin/master -d
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopwaitsecs=10
stdout_logfile=/var/log/supervisor-postfix.log
stderr_logfile=/var/log/supervisor-postfix-err.log
